### ISSUE TITLE
Yoshi Neutral Special Crashes Game (Ryujinx)

### ISSUE THREAD

**Issue by CryoPyroGenetics** [HDR-Development/HDR-Releases#10]
Tested on Bowser only for the moment

I would like to mention that the same crash happened when you get jab-locked by Banjo Neutral Special, but I haven't tested this one yet.

**Comment by ohdangthejam** [comment]
Updating SSBU from 3.0.0 to 3.0.1 fixes this crash. Ike/Chrom/Mithra up+b also crash the game if you have not updated.

**Comment by CryoPyroGenetics** [comment]
> Updating SSBU from 3.0.0 to 3.0.1 fixes this crash. Ike/Chrom/Mithra up+b also crash the game if you have not updated.

Okay, this seems upgrading from 13.0.0 to 13.0.1 has indeed fixed the problems listed
- Terry Down-B
- Ike/Chrom/Pyra Up-B
- Yoshi Neutral-B
